In [1]:
import pandas as pd

df

In [2]:
df = pd.read_csv(r"C:\Users\xboxn\Documents\QgisProy\DatosEconomicos\rangos_pobreza_loc_urbana_2020.csv", encoding="latin-1")

In [3]:
import pandas as pd


def intervalo_a_cols(intervalo):
    # Si el valor es nulo o vacío
    if pd.isna(intervalo) or str(intervalo).strip() == "":
        return (-1)
    
    intervalo = str(intervalo).strip("[]() ")
    
    try:
        # Intentar dividir por coma
        if "," in intervalo:
            a, b = intervalo.split(",")
        # Intentar dividir por guion
        elif "-" in intervalo:
            a, b = intervalo.split("-")
        else:
            # Solo un valor → regresa -100 en ambos
            return (-1)
        
        return (float(a)/200 + float(b)/200)
    
    except ValueError:
        # Si falla el split o la conversión
        return (-1)

# Crear DataFrame

def construir_clave_mun(row):
    text=str(row["CVE_MUN"])
    mun = text[-3:]
    
    return mun


def construir_clave_loc(row):
    text=str(row["CVE_LOC"])
    loc= text[-3:]
    
    return loc

In [4]:
df.dropna(inplace=True)
df['rango_pobreza']=df.rango_pobreza.map(intervalo_a_cols)

In [5]:
df = df[df["rango_pobreza"] != -1] #valores nulos o faltantes

In [6]:
df

,ï»¿clave_entidad,entidad_federativa,clave_municipio,municipio,clave_localidad,localidad,poblacionITER,rango_pobreza,entidad
0,1,Aguascalientes,1001,Aguascalientes,10010001,Aguascalientes,863893,0.3,Aguascalientes
1,1,Aguascalientes,1001,Aguascalientes,10010237,Jaltomate,2805,0.5,Aguascalientes
2,1,Aguascalientes,1001,Aguascalientes,10010239,General JosÃ© MarÃ­a Morelos y PavÃ³n (CaÃ±ada...,3822,0.3,Aguascalientes
3,1,Aguascalientes,1001,Aguascalientes,10010293,Norias de Ojocaliente,4476,0.5,Aguascalientes
4,1,Aguascalientes,1001,Aguascalientes,10010357,Norias del Paso Hondo,3362,0.7,Aguascalientes
...,...,...,...,...,...,...,...,...,...
5237,32,Zacatecas,32055,Villanueva,320550042,Malpaso,3910,0.7,Zacatecas
5238,32,Zacatecas,32056,Zacatecas,320560001,Zacatecas,138444,0.3,Zacatecas
5239,32,Zacatecas,32056,Zacatecas,320560028,Cieneguillas,2753,0.3,Zacatecas
5240,32,Zacatecas,32057,Trancoso,320570001,Trancoso,17021,0.5,Zacatecas
5241,32,Zacatecas,32058,Santa MarÃ­a de la Paz,320580001,Santa MarÃ­a de la Paz,1995,0.5,Zacatecas

In [7]:
df = df.rename(columns={
    "ï»¿clave_entidad": "CVE_ENT",
    "clave_municipio": "CVE_MUN",
    "clave_localidad": "CVE_LOC",
    "rango_pobreza":"pobreza"
})

In [8]:
df['CVE_MUN'] = df.apply(construir_clave_mun, axis=1)
df['CVE_LOC'] = df.apply(construir_clave_loc, axis=1)

df["CVE_MUN"] = pd.to_numeric(df["CVE_MUN"], errors="coerce").astype("Int64")
df["CVE_LOC"] = pd.to_numeric(df["CVE_LOC"], errors="coerce").astype("Int64")

In [9]:
df

,CVE_ENT,entidad_federativa,CVE_MUN,municipio,CVE_LOC,localidad,poblacionITER,pobreza,entidad
0,1,Aguascalientes,1,Aguascalientes,1,Aguascalientes,863893,0.3,Aguascalientes
1,1,Aguascalientes,1,Aguascalientes,237,Jaltomate,2805,0.5,Aguascalientes
2,1,Aguascalientes,1,Aguascalientes,239,General JosÃ© MarÃ­a Morelos y PavÃ³n (CaÃ±ada...,3822,0.3,Aguascalientes
3,1,Aguascalientes,1,Aguascalientes,293,Norias de Ojocaliente,4476,0.5,Aguascalientes
4,1,Aguascalientes,1,Aguascalientes,357,Norias del Paso Hondo,3362,0.7,Aguascalientes
...,...,...,...,...,...,...,...,...,...
5237,32,Zacatecas,55,Villanueva,42,Malpaso,3910,0.7,Zacatecas
5238,32,Zacatecas,56,Zacatecas,1,Zacatecas,138444,0.3,Zacatecas
5239,32,Zacatecas,56,Zacatecas,28,Cieneguillas,2753,0.3,Zacatecas
5240,32,Zacatecas,57,Trancoso,1,Trancoso,17021,0.5,Zacatecas
5241,32,Zacatecas,58,Santa MarÃ­a de la Paz,1,Santa MarÃ­a de la Paz,1995,0.5,Zacatecas

In [10]:
dfmx=df[df["CVE_ENT"]==20]
dfmx

,CVE_ENT,entidad_federativa,CVE_MUN,municipio,CVE_LOC,localidad,poblacionITER,pobreza,entidad
2774,20,Oaxaca,1,Abejones,1,Abejones,841,0.9,Oaxaca
2775,20,Oaxaca,2,AcatlÃ¡n de PÃ©rez Figueroa,1,AcatlÃ¡n de PÃ©rez Figueroa,6341,0.5,Oaxaca
2776,20,Oaxaca,2,AcatlÃ¡n de PÃ©rez Figueroa,12,Cerro Mojarra,2509,0.9,Oaxaca
2777,20,Oaxaca,2,AcatlÃ¡n de PÃ©rez Figueroa,37,Tetela,3100,0.5,Oaxaca
2778,20,Oaxaca,2,AcatlÃ¡n de PÃ©rez Figueroa,39,Vicente Camalote,7024,0.5,Oaxaca
...,...,...,...,...,...,...,...,...,...
3389,20,Oaxaca,566,San Mateo Yucutindoo,9,San Mateo Yucutindoo,835,0.9,Oaxaca
3390,20,Oaxaca,567,ZapotitlÃ¡n Lagunas,1,ZapotitlÃ¡n Lagunas,1643,0.7,Oaxaca
3391,20,Oaxaca,568,ZapotitlÃ¡n Palmas,1,ZapotitlÃ¡n Palmas,1301,0.7,Oaxaca
3392,20,Oaxaca,569,Santa InÃ©s de Zaragoza,1,Santa InÃ©s de Zaragoza,237,0.7,Oaxaca
3393,20,Oaxaca,570,ZimatlÃ¡n de Ãlvarez,1,ZimatlÃ¡n de Ãlvarez,14226,0.7,Oaxaca

In [11]:
df_loc=pd.read_csv('C:/Users/xboxn/Documents/QgisProy/DatosEconomicos/pobreza.csv')

In [12]:
import pandas as pd
df_vivienda=pd.read_csv('C:/Users/xboxn/Documents/QgisProy/DatosEconomicos/viviendas.csv')
df_ingresos=pd.read_csv('C:/Users/xboxn/Documents/QgisProy/DatosEconomicos/ingresos_hogar.csv')

C:\Users\xboxn\AppData\Local\Temp\ipykernel_37884\2291281281.py:2: DtypeWarning: Columns (1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vivienda=pd.read_csv('C:/Users/xboxn/Documents/QgisProy/DatosEconomicos/viviendas.csv')

In [13]:
df= df_ingresos.merge(
    df_vivienda,
    on=["folioviv"],
    how="inner"
)

In [14]:
df

,folioviv,foliohog,numren,clave,mes_1,mes_2,mes_3,mes_4,mes_5,mes_6,...,tot_hom,tot_muj,tot_hog,ubica_geo,tam_loc,est_socio,est_dis,upm,factor,procaptar
0,100013605,1,1,P022,10.0,9.0,8.0,7.0,6.0,5.0,...,1,2,1,1001,1,3,2,1,182,0
1,100013605,1,1,P040,10.0,9.0,8.0,7.0,6.0,5.0,...,1,2,1,1001,1,3,2,1,182,0
2,100013605,1,1,P049,10.0,9.0,8.0,7.0,6.0,5.0,...,1,2,1,1001,1,3,2,1,182,0
3,100013605,1,1,P069,10.0,9.0,8.0,7.0,6.0,5.0,...,1,2,1,1001,1,3,2,1,182,0
4,100013605,1,2,P022,10.0,9.0,8.0,7.0,6.0,5.0,...,1,2,1,1001,1,3,2,1,182,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394907,3260770717,1,4,P001,9.0,8.0,7.0,6.0,5.0,4.0,...,3,4,1,32012,4,2,558,10149,129,0
394908,3260770718,1,1,P040,9.0,8.0,7.0,6.0,5.0,4.0,...,2,1,1,32012,4,2,558,10149,129,0
394909,3260770718,1,2,P001,9.0,8.0,7.0,6.0,5.0,4.0,...,2,1,1,32012,4,2,558,10149,129,0
394910,3260770718,1,3,P001,9.0,8.0,7.0,6.0,5.0,4.0,...,2,1,1,32012,4,2,558,10149,129,0
394911,3260770718,1,3,P009,NaN,NaN,NaN,NaN,NaN,NaN,...,2,1,1,32012,4,2,558,10149,129,0

In [15]:
import numpy as np

# 1. Definimos la lista de columnas que vamos a evaluar
cols_ing = ['ing_1', 'ing_2', 'ing_3', 'ing_4', 'ing_5', 'ing_6']

# 2. Reemplazamos los 0 por NaN, y calculamos el promedio por fila (axis=1)
df['promedio_ing_mensual'] = df[cols_ing].replace(0, np.nan).mean(axis=1)

# 3. (Opcional) Si un hogar tiene ceros en TODOS los meses, el resultado será NaN. 
# Si prefieres que en esos casos vuelva a decir 0 en lugar de NaN, descomenta la siguiente línea:
# df['promedio_ing_mensual'] = df['promedio_ing_mensual'].fillna(0)

# Mostramos el resultado para comprobar
df[['ing_1', 'ing_2', 'ing_3', 'ing_4', 'ing_5', 'ing_6', 'promedio_ing_mensual']]

,ing_1,ing_2,ing_3,ing_4,ing_5,ing_6,promedio_ing_mensual
0,0.000000,2736.348973,2736.348973,2736.348973,2736.348973,0.000000,2736.348973
1,256.532716,256.532716,256.532716,256.532716,256.532716,256.532716,256.532716
2,0.000000,0.000000,0.000000,0.000000,0.000000,855.109054,855.109054
3,2736.348973,0.000000,0.000000,0.000000,0.000000,0.000000,2736.348973
4,0.000000,0.000000,9406.199595,0.000000,0.000000,0.000000,9406.199595
...,...,...,...,...,...,...,...
394907,2543.282862,1544.136023,0.000000,0.000000,0.000000,0.000000,2043.709443
394908,467.536768,467.536768,467.536768,935.073537,935.073537,467.536768,623.382358
394909,4488.352977,4488.352977,4488.352977,4488.352977,4488.352977,4488.352977,4488.352977
394910,6545.514758,6545.514758,6545.514758,6545.514758,6545.514758,6545.514758,6545.514758
394911,9350.735368,NaN,NaN,NaN,NaN,NaN,9350.735368

In [16]:
import pandas as pd

# Asegurarnos de que estim_pago sea numérico por si hay espacios o errores de formato
df['estim_pago'] = pd.to_numeric(df['estim_pago'], errors='coerce')

# ---------------------------------------------------------
# PARTE A: Clasificación por ingresos (Clase Baja, Media, Alta)
# ---------------------------------------------------------

# ---------------------------------------------------------
# PARTE B: Conteo de estrato socioeconómico y estadística de estim_pago
# ---------------------------------------------------------

# 1. Contar el número de hogares por cada est_socio
df_est_socio = df.groupby('ubica_geo')['est_socio'].value_counts().unstack(fill_value=0)
df_est_socio.columns.name = None
# Renombramos para que sea fácil de identificar (suponiendo estratos del 1 al 4)
df_est_socio.columns = [f'est_socio_{int(col)}' for col in df_est_socio.columns]

# 2. Calcular media y desviación estándar de estim_pago
# Usamos .agg() para calcular múltiples estadísticas a la vez
df_estim_pago = df.groupby('ubica_geo')['promedio_ing_mensual'].agg(['mean'])

df_estim_pago['EstimPagoPromedio']=df_estim_pago['mean']
df_estim_pago=df_estim_pago['EstimPagoPromedio']
# ---------------------------------------------------------

df_final = pd.concat([ df_est_socio, df_estim_pago], axis=1).reset_index()


df_final = df_final.rename(columns={
    'est_socio_1': 'cantidadHogares_ClaseBaja', 
    'est_socio_2': 'cantidadHogares_ClaseMediaBaja', 
    'est_socio_3': 'cantidadHogares_ClaseMediaAlta', 
    'est_socio_4': 'cantidadHogares_claseAlta'
})
# Mostramos los primeros resultados
df_final

,ubica_geo,cantidadHogares_ClaseBaja,cantidadHogares_ClaseMediaBaja,cantidadHogares_ClaseMediaAlta,cantidadHogares_claseAlta,EstimPagoPromedio
0,1001,0,3488,3176,1235,6219.543746
1,1002,0,521,0,0,4507.893945
2,1003,0,701,0,0,5938.524013
3,1004,0,136,0,0,3986.714612
4,1005,0,1209,398,0,6113.286514
...,...,...,...,...,...,...
1085,32053,0,219,0,0,5101.001901
1086,32054,80,221,0,0,3725.415437
1087,32055,0,75,0,0,4608.612410
1088,32056,0,346,491,186,6124.621818
1089,32057,0,214,0,0,3810.625017

In [17]:

# 1. Asegurarnos de tratar la columna como texto y quitar decimales si Pandas los agregó
# (A veces los números se leen como 10001.0, esto lo corrige a "10001")
df_final['ubica_geo_str'] = df_final['ubica_geo'].fillna(0).astype(int).astype(str)

# 2. Función para extraer el estado según la longitud
def extraer_estado(codigo):
    if len(codigo) == 4:
        return codigo[:1]  # Primer carácter
    elif len(codigo) == 5:
        return codigo[:2]  # Primeros dos caracteres
    else:
        # Por si hay algún código más corto o con ceros omitidos
        return  '0'

# 3. Aplicamos las reglas para crear las nuevas columnas
df_final['estado'] = df_final['ubica_geo_str'].apply(extraer_estado).astype(int)
df_final['municipio'] = df_final['ubica_geo_str'].apply(lambda x: x[-3:]).astype(int)# Siempre los últimos 3
df_final.drop(columns="ubica_geo_str", inplace=True)
df_final

,ubica_geo,cantidadHogares_ClaseBaja,cantidadHogares_ClaseMediaBaja,cantidadHogares_ClaseMediaAlta,cantidadHogares_claseAlta,EstimPagoPromedio,estado,municipio
0,1001,0,3488,3176,1235,6219.543746,1,1
1,1002,0,521,0,0,4507.893945,1,2
2,1003,0,701,0,0,5938.524013,1,3
3,1004,0,136,0,0,3986.714612,1,4
4,1005,0,1209,398,0,6113.286514,1,5
...,...,...,...,...,...,...,...,...
1085,32053,0,219,0,0,5101.001901,32,53
1086,32054,80,221,0,0,3725.415437,32,54
1087,32055,0,75,0,0,4608.612410,32,55
1088,32056,0,346,491,186,6124.621818,32,56
1089,32057,0,214,0,0,3810.625017,32,57

In [18]:
df_loc

,Unnamed: 0,CVEGEO,CVE_ENT,NOM_ENT,NOM_ABR,CVE_MUN,NOM_MUN,CVE_LOC,NOM_LOC,AMBITO,...,POB_TOTAL,POB_MASCULINA,POB_FEMENINA,TOTAL DE VIVIENDAS HABITADAS,entidad_federativa,municipio,localidad,poblacionITER,pobreza,entidad
0,0,10010001,1,AGUASCALIENTES,AGS.,1,AGUASCALIENTES,1,AGUASCALIENTES,U,...,863893,419168.0,444725.0,246259,Aguascalientes,Aguascalientes,Aguascalientes,863893,0.3,Aguascalientes
1,1,10010237,1,AGUASCALIENTES,AGS.,1,AGUASCALIENTES,237,JALTOMATE,U,...,2805,1367.0,1438.0,655,Aguascalientes,Aguascalientes,Jaltomate,2805,0.5,Aguascalientes
2,2,10010239,1,AGUASCALIENTES,AGS.,1,AGUASCALIENTES,239,GENERAL JOSÉ MARÍA MORELOS Y PAVÓN (CAÑADA HONDA),U,...,3822,1757.0,2065.0,921,Aguascalientes,Aguascalientes,General JosÃ© MarÃ­a Morelos y PavÃ³n (CaÃ±ada...,3822,0.3,Aguascalientes
3,3,10010293,1,AGUASCALIENTES,AGS.,1,AGUASCALIENTES,293,NORIAS DE OJOCALIENTE,U,...,4476,2264.0,2212.0,997,Aguascalientes,Aguascalientes,Norias de Ojocaliente,4476,0.5,Aguascalientes
4,4,10010357,1,AGUASCALIENTES,AGS.,1,AGUASCALIENTES,357,NORIAS DEL PASO HONDO,U,...,3362,1700.0,1662.0,763,Aguascalientes,Aguascalientes,Norias del Paso Hondo,3362,0.7,Aguascalientes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5187,5187,320550042,32,ZACATECAS,ZAC.,55,VILLANUEVA,42,MALPASO,U,...,3910,1907.0,2003.0,979,Zacatecas,Villanueva,Malpaso,3910,0.7,Zacatecas
5188,5188,320560001,32,ZACATECAS,ZAC.,56,ZACATECAS,1,ZACATECAS,U,...,138444,66109.0,72335.0,39739,Zacatecas,Zacatecas,Zacatecas,138444,0.3,Zacatecas
5189,5189,320560028,32,ZACATECAS,ZAC.,56,ZACATECAS,28,CIENEGUILLAS,R,...,2753,1640.0,1113.0,480,Zacatecas,Zacatecas,Cieneguillas,2753,0.3,Zacatecas
5190,5190,320570001,32,ZACATECAS,ZAC.,57,TRANCOSO,1,TRANCOSO,U,...,17021,8345.0,8676.0,3877,Zacatecas,Trancoso,Trancoso,17021,0.5,Zacatecas
5191,5191,320580001,32,ZACATECAS,ZAC.,58,SANTA MARÍA DE LA PAZ,1,SANTA MARÍA DE LA PAZ,U,...,1995,971.0,1024.0,613,Zacatecas,Santa MarÃ­a de la Paz,Santa MarÃ­a de la Paz,1995,0.5,Zacatecas

In [19]:
df_loc2 = df_loc[['CVEGEO', 'CVE_ENT', 'CVE_MUN', 'CVE_LOC', 'LAT_DECIMAL', 'LON_DECIMAL', 'ALTITUD']].copy()
df_loc2

         CVEGEO  CVE_ENT  CVE_MUN  CVE_LOC  LAT_DECIMAL  LON_DECIMAL  ALTITUD
0      10010001        1        1        1    21.879822  -102.296046     1878
1      10010237        1        1      237    22.016097  -102.145016     1935
2      10010239        1        1      239    22.000604  -102.200656     1922
3      10010293        1        1      293    21.889374  -102.217282     1959
4      10010357        1        1      357    21.860453  -102.207155     1969
...         ...      ...      ...      ...          ...          ...      ...
5187  320550042       32       55       42    22.618914  -102.763009     2128
5188  320560001       32       56        1    22.776095  -102.571836     2427
5189  320560028       32       56       28    22.760396  -102.663199     2269
5190  320570001       32       57        1    22.735389  -102.366038     2193
5191  320580001       32       58        1    21.512178  -103.407042     1921

[5192 rows x 7 columns]

In [20]:
# Supongamos que tus columnas se llaman 'CVE_MUN' (municipio) y 'CVE_ENT' (estado)

# Opción 1: obtener todas las combinaciones únicas de municipio-estado
df_mun_est = df_loc2[['CVE_ENT', 'CVE_MUN']].drop_duplicates()

df_mun_est

      CVE_ENT  CVE_MUN
0           1        1
7           1        2
11          1        3
13          1        4
15          1        5
...       ...      ...
5185       32       54
5186       32       55
5188       32       56
5190       32       57
5191       32       58

[2466 rows x 2 columns]

In [21]:
df_final=df_final[['cantidadHogares_ClaseBaja',
       'cantidadHogares_ClaseMediaBaja', 'cantidadHogares_ClaseMediaAlta',
       'cantidadHogares_claseAlta', 'EstimPagoPromedio', 'estado', 'municipio']]

In [22]:
# 1. Renombrar columnas en df_mun_est
df_mun_est = df_mun_est.rename(columns={
    'CVE_ENT': 'estado',
    'CVE_MUN': 'municipio'
})

# 2. Merge con df_final
df_mun_estados = df_mun_est.merge(
    df_final,
    on=['estado', 'municipio'],
    how='left'
)

# 3. Calcular promedio municipal (por estado y municipio)
promedios = df_final.groupby(['estado','municipio']).mean().reset_index()


# 5. Rellenar valores faltantes con el promedio municipal
cols = [
    'cantidadHogares_ClaseBaja',
    'cantidadHogares_ClaseMediaBaja',
    'cantidadHogares_ClaseMediaAlta',
    'cantidadHogares_claseAlta',
    'EstimPagoPromedio'
]

# 1. Reemplazar ceros por NaN
df_mun_estados[cols] = df_mun_estados[cols].replace(0, np.nan)

# 2. Calcular promedios por estado
promedios_estado = df_mun_estados.groupby('estado')[cols].transform('mean')
promedios_estado.fillna(0, inplace=True)
# 3. Rellenar NaN con el promedio del mismo estado
for col in cols:
    df_mun_estados[col] = df_mun_estados[col].fillna(promedios_estado[col])


# 6. (Opcional) ordenar
df_mun_estados = df_mun_estados.sort_values(by=['estado','municipio']).reset_index(drop=True)

In [23]:
df_mun_estados

,estado,municipio,cantidadHogares_ClaseBaja,cantidadHogares_ClaseMediaBaja,cantidadHogares_ClaseMediaAlta,cantidadHogares_claseAlta,EstimPagoPromedio
0,1,1,0.000000,3488.000,3176.00,1235.0,6219.543746
1,1,2,0.000000,521.000,960.25,1235.0,4507.893945
2,1,3,0.000000,701.000,960.25,1235.0,5938.524013
3,1,4,0.000000,136.000,960.25,1235.0,3986.714612
4,1,5,0.000000,1209.000,398.00,1235.0,6113.286514
...,...,...,...,...,...,...,...
2461,32,54,80.000000,221.000,280.75,254.0,3725.415437
2462,32,55,107.916667,75.000,280.75,254.0,4608.612410
2463,32,56,107.916667,346.000,491.00,186.0,6124.621818
2464,32,57,107.916667,214.000,280.75,254.0,3810.625017
2465,32,58,107.916667,212.375,280.75,254.0,4963.624032

In [24]:
df_mun_estados.to_csv("INGRESOS_MUNICIPIO.csv")

In [25]:
# Exportamos los datos municipales
df_final.to_csv('datos_municipales_ingresos.csv', index=False, encoding='utf-8')
print("Archivo exportado y listo para QGIS")

Archivo exportado y listo para QGIS

In [26]:
df=pd.read_csv('C:/Users/xboxn/Documents/QgisProy/DatosEconomicos/INGRESOS_MUNICIPIO.csv')
df["CVE"]=df["estado"]*1000+df["municipio"]

In [29]:
df=df[['CVE', 'estado', 'municipio', 'cantidadHogares_ClaseBaja',
       'cantidadHogares_ClaseMediaBaja', 'cantidadHogares_ClaseMediaAlta',
       'cantidadHogares_claseAlta', 'EstimPagoPromedio']]

In [31]:
df.to_csv('INGRESOS_MUNICIPIO.csv')